---
name: CI

on:
  push:

jobs:
  lint-all:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast:
    name: Static Code Analysis Tests
    runs-on: ubuntu-latest
    needs:
      - lint-all
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run static code analysis
        run: |
          pip3 install -r requirements.txt
          bandit app.py

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs:
      - sast
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run unit tests
        run: |
          pip3 install -r requirements.txt
          python -m pytest
